class TestException(Exception):
    """ Internal exception class """
